# Generated by Django 5.2.7 on 2025-10-28 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid Nepali 10-digit mobile number starting with 97 or 98.', regex='^(97|98)\\d{8}$')]),
        ),
    ]
